// <auto-generated>

using System;

namespace Source.Presentation.Transitions
{
    [Serializable]
    public class GameplayPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.Presentation.Panels.GameplayPanel);
    }
}
