// <auto-generated>

using System;

namespace Source.Presentation.Transitions
{
    [Serializable]
    public class LoadingProgressPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.Presentation.Panels.LoadingProgressPanel);
    }
}
