// <auto-generated>

using System;

namespace Source.Presentation.Transitions
{
    [Serializable]
    public class MainMenuPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.Presentation.Screens.MainMenuPanel);
    }
}
