// <auto-generated>

using System;

namespace Source.Presentation.Transitions
{
    [Serializable]
    public class PausePopupType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.Presentation.Popups.PausePopup);
    }
}
