// <auto-generated>

using System;

namespace Source.Presentation.Transitions
{
    [Serializable]
    public class SettingsPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.Presentation.Screens.SettingsPanel);
    }
}
