using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using Yans.UI.Screen;

namespace Source.UI.Transitions.Editor
{
    [InitializeOnLoad]
    public static class UIScreenTypeGenerator
    {
        static UIScreenTypeGenerator()
        {
            AssemblyReloadEvents.afterAssemblyReload += GenerateIfNeeded;
        }

        #region private methods

        private static void GenerateIfNeeded()
        {
            string generatorScriptPath = AssetDatabase
                .FindAssets("UIScreenTypeGenerator t:Script")
                .Select(AssetDatabase.GUIDToAssetPath)
                .FirstOrDefault();

            if (string.IsNullOrEmpty(generatorScriptPath))
            {
                Debug.LogWarning("UIScreenTypeGenerator script not found.");
                return;
            }

            string baseFolder = Path.GetDirectoryName(generatorScriptPath);
            string outputFolder = Path.Combine(baseFolder, "../ScreenTypeRefrences/");
            string absoluteOutput = Path.GetFullPath(outputFolder);

            Directory.CreateDirectory(absoluteOutput);

            var allUIScreenTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(asm => asm.GetTypes())
                .Where(t => typeof(UIScreen).IsAssignableFrom(t) && !t.IsAbstract)
                .ToList();

            foreach (var screen in allUIScreenTypes)
            {
                string wrapperName = screen.Name + "Type";
                string filePath = Path.Combine(absoluteOutput, $"{wrapperName}.cs");

                if (File.Exists(filePath))
                    continue;

                string file = $@"// <auto-generated>

using System;

namespace Source.UI.Transitions
{{
    [Serializable]
    public class {wrapperName} : UIScreenType
    {{
        public override Type GetScreenType() => typeof({screen.FullName});
    }}
}}
";
                File.WriteAllText(filePath, file);
            }

            AssetDatabase.Refresh();
            Debug.Log($"[UIScreenTypeGenerator] Types updated: {allUIScreenTypes.Count}");
        }

        #endregion
    }
}