// <auto-generated>

using System;

namespace Source.UI.Transitions
{
    [Serializable]
    public class GameplayPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.UI.Screens.GameplayPanel);
    }
}
