// <auto-generated>

using System;

namespace Source.UI.Transitions
{
    [Serializable]
    public class MainMenuPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.UI.Screens.MainMenuPanel);
    }
}
