// <auto-generated>

using System;

namespace Source.UI.Transitions
{
    [Serializable]
    public class PausePopupType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.UI.Popups.PausePopup);
    }
}
