// <auto-generated>

using System;

namespace Source.UI.Transitions
{
    [Serializable]
    public class SettingsPanelType : UIScreenType
    {
        public override Type GetScreenType() => typeof(Source.UI.Screens.SettingsPanel);
    }
}
